In [15]:
import torch

w = torch.tensor([[1.0, 5.0], [2.0, 6.0]], requires_grad=True)
x = torch.tensor([[3.0, 7.0], [4.0, 8.0]], requires_grad=True)
a = torch.add(w, x)
b = torch.add(w, 1)
y = torch.mul(a, b)
print(a)
print(b)
print(y)
y.sum().backward()
print(w.grad)

tensor([[ 4., 12.],
        [ 6., 14.]], grad_fn=<AddBackward0>)
tensor([[2., 6.],
        [3., 7.]], grad_fn=<AddBackward0>)
tensor([[ 8., 72.],
        [18., 98.]], grad_fn=<MulBackward0>)
tensor([[ 6., 18.],
        [ 9., 21.]])
