In [13]:
import torch.nn.functional as F
import torch
a = torch.tensor([[1., 2.],
                [3., 4.],
                [5., 6.]])

b = a.unsqueeze(1)
a = a.unsqueeze(0)

print(a)
print(b)

# 计算余弦相似度，得到形状为 (32, 1, 128, 128) 的张量
cos_sim = torch.nn.functional.cosine_similarity(a, b, dim=-1)
print(cos_sim)

# 取出每个样本的余弦相似度矩阵，得到形状为 (32, 128, 128) 的张量
cos_sim = cos_sim.squeeze(1)
print(cos_sim)

tensor([[[1., 2.],
         [3., 4.],
         [5., 6.]]])
tensor([[[1., 2.]],

        [[3., 4.]],

        [[5., 6.]]])
tensor([[1.0000, 0.9839, 0.9734],
        [0.9839, 1.0000, 0.9987],
        [0.9734, 0.9987, 1.0000]])
tensor([[1.0000, 0.9839, 0.9734],
        [0.9839, 1.0000, 0.9987],
        [0.9734, 0.9987, 1.0000]])


In [23]:
# 获取对角线上的值
diag = torch.diag(cos_sim)
print(diag)
# 获取非对角线上的值
others_sum = torch.sum(cos_sim - torch.diag(diag))
print(others_sum)
# 计算均值
mean_others = others_sum/(cos_sim.shape[0]*(cos_sim.shape[0]-1))
print(mean_others)

tensor([1.0000, 1.0000, 1.0000])
tensor(5.9119)
tensor(0.9853)
