In [86]:
import os
import numpy as np
from osgeo import gdal

def save_tiff_as_numpy(tiff_file, output_dir, verified_mat):
    # Create saving directory
    if os.path.exists(output_dir)==False:
        os.makedirs(output_dir, exist_ok=True)

    # Open the TIFF file
    dataset = gdal.Open(tiff_file)

    # Loop over all bands in the TIFF file
    for i in range(dataset.RasterCount):
        # Read the band data as a NumPy array
        band = dataset.GetRasterBand(i+1)
        data = band.ReadAsArray()
#         print(np.count_nonzero(verified_mat==1))
        data = data[verified_mat==1]
        index = np.where(verified_mat == 1)
        print(index)
        for j,val in enumerate(data):
            # Construct the output file name
            output_file = os.path.join(output_dir, f"{index[0][j]}_{index[1][j]}.npy")
            print(output_file)

            # Save the data as a NumPy file
            np.save(output_file, val)

    # Close the dataset
#     dataset = None


In [87]:
tiff_file = "E:\\downscaling\\Soil_moisture_downscale_czt\\SMAP\\SMAP_L3_SM_P_E_20150401_PM.tif"
output_dir = "E:\\downscaling\\Soil_moisture_downscale_czt\\SMAP\\20150401"

In [88]:
verified_mat = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         ])
verified_mat[0][2:7] = 1
verified_mat[1][0:8] = 1
verified_mat[2][0:10] = 1
verified_mat[3][0:12] = 1
verified_mat[4][2:13] = 1
verified_mat[5][6:13] = 1
verified_mat[6][7:12] = 1
print(verified_mat)

[[0 0 1 1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 1 1 1 1 1 0]]


In [91]:
save_tiff_as_numpy(tiff_file, output_dir, verified_mat)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6], dtype=int64), array([ 2,  3,  4,  5,  6,  0,  1,  2,  3,  4,  5,  6,  7,  0,  1,  2,  3,
        4,  5,  6,  7,  8,  9,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  6,  7,  8,  9, 10,
       11, 12,  7,  8,  9, 10, 11], dtype=int64))
E:\downscaling\Soil_moisture_downscale_czt\SMAP\20150401\0_2.npy
E:\downscaling\Soil_moisture_downscale_czt\SMAP\20150401\0_3.npy
E:\downscaling\Soil_moisture_downscale_czt\SMAP\20150401\0_4.npy
E:\downscaling\Soil_moisture_downscale_czt\SMAP\20150401\0_5.npy
E:\downscaling\Soil_moisture_downscale_czt\SMAP\20150401\0_6.npy
E:\downscaling\Soil_moisture_downscale_czt\SMAP\20150401\1_0.npy
E:\downscaling\Soil_moisture_downscale_czt\SMAP\20150401\1_1.npy
E:\downscaling\Soil_moisture_downscale_czt\SMAP\20150401\1_

In [90]:
array = np.load("E:\\downscaling\\Soil_moisture_downscale_czt\\SMAP\\20150401\\0.npy")
print(np.amin(array))
print(np.amax(array))

0.15427671
0.15427671
