In [122]:
def normalization(array_2d):
    mean = np.mean(array_2d)
    std = np.std(array_2d)
    print(mean)
    print(std)
    return (array_2d - mean) / std

In [123]:
import pandas as pd
import numpy as np

In [124]:
df = pd.read_csv('E:\\downscaling\\Soil_moisture_downscale_czt\\Babao_Soil_Point_Properties.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7296 entries, 0 to 7295
Data columns (total 60 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   OBJECTID            7296 non-null   int64  
 1   pointid             7296 non-null   int64  
 2   grid_code           7296 non-null   int64  
 3   ID                  7296 non-null   int64  
 4   MU_GLOBAL           7296 non-null   int64  
 5   MU_SOURCE1          7296 non-null   int64  
 6   MU_SOURCE2          0 non-null      float64
 7   ISSOIL              7296 non-null   int64  
 8   SHARE               7296 non-null   int64  
 9   SEQ                 7296 non-null   int64  
 10  SU_SYM74            0 non-null      float64
 11  SU_CODE74           0 non-null      float64
 12  SU_SYM85            0 non-null      float64
 13  SU_CODE85           0 non-null      float64
 14  SU_SYM90            7296 non-null   object 
 15  SU_CODE90           7296 non-null   int64  
 16  T_TEXT

In [125]:
filter_index = list(range(16)) 
filter_index.append(33)
filter_index = np.asarray(filter_index) + 26
print(filter_index)

[26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 59]


In [126]:
t_features = df.iloc[:,filter_index]

In [131]:
out_dir = 'E:\\downscaling\\Soil_moisture_downscale_czt\\DATASET\\INPUT\\TEXTURE\\'
for i in range(df['RASTERINDEX'].max()+1):
    filename = f'{i}.npy'
    t_features_i = np.asarray(t_features[t_features['RASTERINDEX']==i].iloc[:121, :16])
    print(t_features_i)
    t_features_i = normalization(t_features_i)
    print(t_features_i)
    np.save(out_dir + filename, t_features_i)

[[13.  56.  38.  ...  0.   0.   0.1]
 [13.  56.  38.  ...  0.   0.   0.1]
 [13.  56.  38.  ...  0.   0.   0.1]
 ...
 [13.  56.  38.  ...  0.   0.   0.1]
 [13.  56.  38.  ...  0.   0.   0.1]
 [ 6.  35.  45.  ...  0.   2.   0.1]]
17.804524793388428
23.404827290041215
[[-0.20527922  1.6319486   0.86287649 ... -0.7607202  -0.7607202
  -0.75644757]
 [-0.20527922  1.6319486   0.86287649 ... -0.7607202  -0.7607202
  -0.75644757]
 [-0.20527922  1.6319486   0.86287649 ... -0.7607202  -0.7607202
  -0.75644757]
 ...
 [-0.20527922  1.6319486   0.86287649 ... -0.7607202  -0.7607202
  -0.75644757]
 [-0.20527922  1.6319486   0.86287649 ... -0.7607202  -0.7607202
  -0.75644757]
 [-0.50436282  0.7346978   1.16196009 ... -0.7607202  -0.67526774
  -0.75644757]]
[[13.  56.  38.  ...  0.   0.   0.1]
 [13.  56.  38.  ...  0.   0.   0.1]
 [13.  56.  38.  ...  0.   0.   0.1]
 ...
 [13.  56.  38.  ...  0.   0.   0.1]
 [13.  56.  38.  ...  0.   0.   0.1]
 [13.  56.  38.  ...  0.   0.   0.1]]
16.02625
21.0335879

[[24.  46.  34.  ...  0.   1.   0.1]
 [24.  46.  34.  ...  0.   1.   0.1]
 [24.  46.  34.  ...  0.   1.   0.1]
 ...
 [17.  31.  49.  ...  0.   3.   0.1]
 [17.  31.  49.  ...  0.   3.   0.1]
 [17.  31.  49.  ...  0.   3.   0.1]]
18.108796487603307
22.082653123083976
[[ 0.2667797   1.2630368   0.71962383 ... -0.82004623 -0.77476182
  -0.81551779]
 [ 0.2667797   1.2630368   0.71962383 ... -0.82004623 -0.77476182
  -0.81551779]
 [ 0.2667797   1.2630368   0.71962383 ... -0.82004623 -0.77476182
  -0.81551779]
 ...
 [-0.0502112   0.58377059  1.39889004 ... -0.82004623 -0.68419299
  -0.81551779]
 [-0.0502112   0.58377059  1.39889004 ... -0.82004623 -0.68419299
  -0.81551779]
 [-0.0502112   0.58377059  1.39889004 ... -0.82004623 -0.68419299
  -0.81551779]]
[[28.  35.  33.  ...  0.   1.   0.1]
 [28.  35.  33.  ...  0.   1.   0.1]
 [28.  35.  33.  ...  0.   1.   0.1]
 ...
 [17.  31.  49.  ...  0.   3.   0.1]
 [17.  31.  49.  ...  0.   3.   0.1]
 [17.  31.  49.  ...  0.   3.   0.1]]
21.72696797520